ODROIDC4-UBOOT-CONFIG

setenv bootlabel "Yocto"

setenv board "odroidc4"
setenv display_autodetect "true"

# Set load addresses
setenv dtb_loadaddr "0x10000000"
setenv dtbo_addr_r "0x11000000"
setenv k_addr "0x1100000"
setenv loadaddr "0x8000000"
setenv initrd_loadaddr "0x3700000"

setenv condev "console=ttyAML0,115200n8"   # on both

# Boot Args
setenv bootargs "root=/dev/mmcblk1p3 rootwait rw no_console_suspend ${condev} cma=512M"

# Load kernel, dtb and initrd
load mmc ${devno}:1 ${k_addr} Image.gz
load mmc ${devno}:1 ${dtb_loadaddr} amlogic/meson64_odroidc4.dtb
fdt addr ${dtb_loadaddr}

# unzip the kernel
unzip ${k_addr} ${loadaddr}

# boot
booti ${loadaddr} - ${dtb_loadaddr}
