#!/bin/sh
### BEGIN INIT INFO
# Provides:          odroid-c4-audio-routing
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: ODROID-C4 HDMI audio routing
### END INIT INFO

case "$1" in
	start)
		/usr/bin/odroid-c4-audio-routing.sh
		;;
	stop|restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac
exit 0
