#!/bin/bash

GATE_INTERNET="1"
NTP="0"
NTP_SERVER="time.google.com"
URL="http://claro.mdrjr.me/video/index.html"

if test -e /boot/autostart.cfg; then
    . /boot/autostart.cfg
fi

if [ "$GATE_INTERNET" -eq "1" ]; then
        while [ -z "$(/sbin/ip -4 route show default 2>/dev/null)" ]; do sleep 1; echo .; done
fi

if [ "$NTP" -eq "1" ]; then
    /usr/sbin/ntpdate $NTP_SERVER
fi

sleep 1

/usr/bin/chromium --noerrdialogs --no-first-run --kiosk --start-fullscreen --autoplay-policy=no-user-gesture-required $URL
