# Copyright (c) 2026, Hardkernel Co., Ltd
# Released under the MIT license (see COPYING.MIT for the terms)

#@TYPE: Machine
#@NAME: ODROID-N2-Plus
#@DESCRIPTION: Machine configuration for the ODROID-N2-Plus (Amlogic S922X)

require conf/machine/include/arm/armv8a/tune-cortexa73-cortexa53.inc
require conf/machine/odroid.inc

PREFERRED_PROVIDER_virtual/bootloader ?= "u-boot-odroid-n2"
PREFERRED_PROVIDER_virtual/kernel ?= "linux-odroid-c4"
PREFERRED_VERSION_linux-odroid-c4 := "7.0%"

KERNEL_IMAGETYPE = "Image.gz"

KERNEL_DEVICETREE = "amlogic/meson64_odroidn2_plus.dtb"
IMAGE_BOOT_FILES = "Image.gz meson64_odroidn2_plus.dtb;amlogic/meson64_odroidn2_plus.dtb boot.ini boot-logo.bmp.gz"

SERIAL_CONSOLES = "115200;ttyAML0"

PACKAGECONFIG:remove:pn-perf = "scripting"

RDEPENDS:${KERNEL_PACKAGE_NAME}-base = ""

WKS_FILE ?= "odroid-g12.wks"

PACKAGECONFIG:append:pn-mesa = " gallium gallium-llvm panfrost libclc"
