# Copyright (c) 2026, Hardkernel Co., Ltd
# Released under the MIT license (see COPYING.MIT for the terms)

#@TYPE: Machine
#@NAME: ODROID-C4
#@DESCRIPTION: Machine configuration for the ODROID-C4 (Amlogic S905X3)

require conf/machine/include/arm/armv8-2a/tune-cortexa55.inc
require conf/machine/odroid.inc

PREFERRED_PROVIDER_virtual/kernel ?= "linux-odroid-c4"
PREFERRED_VERSION_linux-odroid-c4 := "7.0%"

KBUILD_DEFCONFIG := "defconfig"

KERNEL_DEVICETREE = "amlogic/meson-sm1-odroid-c4.dtb"
IMAGE_BOOT_FILES += "Image amlogic/meson-sm1-odroid-c4.dtb"

PACKAGECONFIG:remove:pn-perf = "scripting"

RDEPENDS:${KERNEL_PACKAGE_NAME}-base = ""

# TODO: u-boot recipe (PREFERRED_PROVIDER_virtual/bootloader)
# TODO: libmali Mali-G31 (require conf/machine/mali-c4.inc)
# TODO: WKS_FILE = "odroid-c4.wks"
