#!/bin/sh
### BEGIN INIT INFO
# Provides:          odroid-zram
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: zram swap device
### END INIT INFO

case "$1" in
	start)
		/usr/bin/odroid-zram.sh
		;;
	stop)
		swapoff /dev/zram0 2>/dev/null || true
		;;
	restart|reload)
		"$0" stop; "$0" start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
exit 0
