amlogic-dvb-demux
encoder_common

amvdec_mmjpeg
amvdec_h264mvc
amvdec_h265
amvdec_mmpeg4
amvdec_mavs
amvdec_mmpeg12
amvdec_vp9_fb
amvdec_mh264
amvdec_av1_fb
amvdec_vc1
amvdec_debug_port
decoder_common
amvdec_vp9
amvdec_avs3
amvdec_avs2_fb
amvdec_h265_fb
amvdec_av1
amvdec_avs2

amvdec_mmjpeg_v4l
amvdec_h265_v4l
amvdec_mmpeg4_v4l
amvdec_mavs_v4l
amvdec_av1_t5d_v4l
amvdec_mmpeg12_v4l
amvdec_vp9_fb_v4l
amvdec_mh264_v4l
amvdec_av1_fb_v4l
amvdec_vc1_v4l
amvdec_vp9_v4l
amvdec_avs3_v4l
amvdec_avs2_fb_v4l
amvdec_h265_fb_v4l
amvdec_av1_v4l
amvdec_avs2_v4l

media_sync
jpegenc
encoder
